name: CI/CD CCMS-Ecommerce

on:
  push:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Tests
      run: |
        docker-compose up -d